### PR TITLE
Todo creation

### PR DESCRIPTION
**Pull request by El-Potato-Slayer**
- Contains a welcome page if there are no categories
- Users can create categories
- Users can add tasks to each category
- Users can delete tasks
- Users can edit tasks
- Users can mark tasks as complete
- Wrote functional tests

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## changes Required

### Hi @El-Potato-Slayer :wave: 

I was not able to run the application locally on my computer. I checked the package.json file, there is no **start** property in the **scripts** object.
* [ ] Also you did not install webpack-dev-server as devDependency in package.json file.
* [ ] The link for the [live demo](https://raw.githack.com/El-Potato-Slayer/js-restaurant/feature/dist/index.html) you provided in your readme file isn't correct. It points to the restaurant page.
* [ ] Edit the title of your readme file.

#### Make these changes then submit another form for a code review.

### Have a great day :slightly_smiling_face: 

#### ``` Uchechukwu Henry Inyama ```

**Comment by El-Potato-Slayer** [comment]
@uche-inyama the command to run the application is `build`. I'll add that to the readme, along with the rest of the changes

**Comment by El-Potato-Slayer** [comment]
@uche-inyama I don't see any instructions that webpack-dev-server has to be added.

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi @El-Potato-Slayer :wave: 

There are few changes to implement.

* [ ] Like I mentioned earlier, webpack-dev-server needs to be installed and added as devDependencies ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/devdep_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622602/)) in your package.json file.

* [ ] Your scripts properties should look like so:

```           

    "scripts": {
        "dev": "webpack --mode development",
        "build": "webpack --mode production",
        "start": "webpack-dev-server --mode development --open" // optional
      },

```

* [ ] According to the project requirement,  there is a 'default' project, when you start the application.([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/projects_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))

#### Make these changes, then submit another form for a code review.


### Have a great day :slightly_smiling_face: 

#### ``` Uchechukwu Inyama Henry ```

**Comment by El-Potato-Slayer** [comment]
> Like I mentioned earlier, webpack-dev-server needs to be installed and added as devDependencies ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/devdep_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622602/)) in your package.json file.

I see nothing of needing to have webpack-dev-server installed. If there's any mention of it, please point me to it. However, if this is a preference rather than a requirement, I will not implement the changes.

**Review by NtwaliHeritier — APPROVED** [review]
### **STATUS: APPROVED✔✔✔**
Hello team,
This is a great implementation of the project.
You can merge and move on👍👌

However as mentioned by the previous TSE, the dependency will allow your webpack to automatically compile and run. If you want, you can implement it as an optional requirement.

Happy coding💻💻💻

**Pull request merged**
